export const UPD_ACCOUNT_CREDENTIALS = 'UPD_ACCOUNT_CREDENTIALS';
export const LOGIN = 'LOGIN';
export const INCOMPLETE_CREDENTIALS = 'INCOMPLETE_CREDENTIALS';
export const REQUEST_BALANCE = 'REQUEST_BALANCE';
export const RECEIVE_BALANCE = 'RECEIVE_BALANCE';
export const LOGOUT = 'LOGOUT';
