export const UPD_ACCOUNT_CREDENTIALS = 'UPD_ACCOUNT_CREDENTIALS';
export const SAVE_ACCOUNT_CREDENTIALS = 'SAVE_ACCOUNT_CREDENTIALS';
export const REQUEST_BALANCE = 'REQUEST_BALANCE';
export const RECEIVE_BALANCE = 'RECEIVE_BALANCE';
export const LOGOUT = 'LOGOUT';
